apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telemetry-db.fullname" . }}-postgres
  labels:
    {{- include "telemetry-db.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  postgres-user: {{ .Values.postgresql.auth.username | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  postgres-db: {{ .Values.postgresql.auth.database | quote }}
  database-url: {{ include "telemetry-db.databaseUrl" . | quote }}
