apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-db.postgresHeadlessServiceName" . }}
  labels:
    {{- include "telemetry-db.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    {{- include "telemetry-db.postgresLabels" . | nindent 4 }}
