-- Atlas versioned migration (initial).
CREATE TABLE IF NOT EXISTS "public"."telemetry" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "metric_name" text NOT NULL,
  "gpu_id" text NOT NULL,
  "device" text NOT NULL,
  "uuid" text NOT NULL,
  "model_name" text NOT NULL,
  "host_name" text NOT NULL,
  "value" double precision NOT NULL,
  "labels_raw" text NOT NULL,
  "processed_at_unix_nano" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_telemetry_uuid" ON "public"."telemetry" ("uuid");

CREATE INDEX IF NOT EXISTS "idx_telemetry_gpu_id" ON "public"."telemetry" ("gpu_id");

CREATE INDEX IF NOT EXISTS "idx_telemetry_host_name" ON "public"."telemetry" ("host_name");
